/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
	// By default, Docusaurus generates a sidebar from the docs folder structure
	guzineSidebar: [{ type: "autogenerated", dirName: "guzine" }],
	breadlySidebar: [{ type: "autogenerated", dirName: "breadly" }],
	qrtenSidebar: [{ type: "autogenerated", dirName: "qrten" }],
	graviaSidebar: [{ type: "autogenerated", dirName: "gravia" }],

	// But you can create a sidebar manually
	/*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

module.exports = sidebars;
